# only with specific commands

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = ["DeinUpdate"]

# only in insert mode

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_post_source = "source ~/.config/nvim/plugins/lexima.vim"

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
depends = ['neosnippet-snippets']
hook_post_source = """
imap <silent><expr> <C-s>
  \ pumvisible() ? "\<C-e>\<Plug>(neosnippet_expand_or_jump)"
  \ : "\<Plug>(neosnippet_expand_or_jump)"
smap <C-s> <Plug>(neosnippet_expand_or_jump)
xmap <C-s> <Plug>(neosnippet_expand_target)
let g:neosnippet#snippets_directory='~/.vim/snippets'
"""

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1


# only in python

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']


# only in LaTeX or TeX

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex', 'plaintex']
hook_post_source = """
let g:vimtex_compiler_latexmk = {'callback' : 0}
" let g:vimtex_imaps_list = []
let g:tex_flavor = "latex"
" let g:vimtex_fold_manual = 1
let g:vimtex_fold_enabled = 1
let g:vimtex_indent_ignored_envs = ['document', 'frame']
let g:vimtex_imaps_leader = "@"
"""

[[plugins]]
repo = 'bps/vim-textobj-python'
# depends = ['kana/vim-textobj-user']
on_ft = ['python']

# only in ReST

[[plugins]]
repo = 'Rykka/riv.vim'
on_ft = ['rst', 'restructuredtext']
hook_source = """
let g:riv_fold_level = 1
let g:riv_fold_info_pos = 'left'
let g:riv_ignored_imaps = "<Tab>"
let g:riv_ignored_nmaps = ">,<"
let g:riv_ignored_maps = "<CR>,<S-CR>"
"""


