# dein.vim config file

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = """
" let g:airline_theme = 'gruvbox'
" let g:airline_theme = 'dracula'
let g:airline_theme = 'sol'
" nmap <C-p> <Plug>AirlineSelectPrevTab
" nmap <C-n> <Plug>AirlineSelectNextTab
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
" let g:airline#extensions#tabline#buffer_idx_mode = 1
" let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
"""

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'mogassy/smooth-scroll.vim'
hook_add = """
let g:smooth_scroll_no_default_key_mappings = 1
let g:smooth_scroll_interval = 1000.0 / 60
let g:smooth_scroll_scrollkind = "quintic"
nnoremap <silent> <C-d> :<C-u>call smooth_scroll#flick(v:count1 * winheight(0) / 2, winheight(0) / 3,  1)<CR>
nnoremap <silent> <C-u> :<C-u>call smooth_scroll#flick(v:count1 * winheight(0) / 2, winheight(0) / 3, -1)<CR>
nnoremap <silent> <C-f> :<C-u>call smooth_scroll#flick(v:count1 * winheight(0)    , winheight(0) / 2,  1)<CR>
nnoremap <silent> <C-b> :<C-u>call smooth_scroll#flick(v:count1 * winheight(0)    , winheight(0) / 2, -1)<CR>
"""

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['kristijanhusak/defx-git']
hook_add = """
source ~/.config/nvim/plugins/defx.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = """
let g:caw_operator_keymappings = 1
map <Space>c gcc
nmap <Space>cc gcc$
"""

[[plugins]]
repo = 'glts/vim-textobj-comment'
depends = ['kana/vim-textobj-user']

[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = """
source ~/.config/nvim/plugins/sandwich.vim
"""

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = "source ~/.config/nvim/plugins/vim-textobj-user.vim"

# [[plugins]]
# repo = 'jsfaint/gen_tags.vim'
# hook_add = """
# let g:gen_tags#ctags_auto_gen = 1
# let g:gen_tags#gtags_auto_gen = 1
# """

[[plugins]]
repo = 'kshenoy/vim-signature'
hook_add = """
let g:SignatureIncludeMarks = 'abcdefghijklmnopqrstuvwxyABCDEFGHIJKLMNOPQRSTUVWXYZ'
"""

# [[plugins]]
# repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'Konfekt/FastFold'


[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.vim
"""


[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']
hook_add = """
let s:local_session_directory = xolox#misc#path#merge(getcwd(), '.vimsessions')
" 存在すれば
if isdirectory(s:local_session_directory)
  " session保存ディレクトリをそのディレクトリの設定
  let g:session_directory = s:local_session_directory
  " vimを辞める時に自動保存
  let g:session_autosave = 'yes'
  " 引数なしでvimを起動した時にsession保存ディレクトリのdefault.vimを開く
  let g:session_autoload = 'yes'
  " 1分間に1回自動保存
  " let g:session_autosave_periodic = 1
else
  let g:session_autosave = 'no'
  let g:session_autoload = 'no'
endif
unlet s:local_session_directory
"""


[[plugins]]
repo = 'xolox/vim-misc'


[[plugins]]
repo = 'qnighy/satysfi.vim'


[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
# build = './install.sh nightly'
build = 'yarn install --frozen-lockfile'
hook_add = """
source ~/.config/nvim/plugins/coc-settings.vim
let g:LanguageClient_serverCommands = {
\   'julia': ['/Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia']}
"""

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = "source ~/.config/nvim/plugins/fugitive.vim"

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = """
let g:polyglot_disabled = ['tex', 'latex']
"""

[[plugins]]
repo = 'jpalardy/vim-slime'
hook_add = """
let g:slime_target = "neovim"
let g:slime_no_mappings = 1
xmap <Space>b <Plug>SlimeRegionSend
nmap <Space>b <Plug>SlimeMotionSend
nmap <Space>bp <Plug>SlimeParagraphSend
nmap <Space>bb <Plug>SlimeLineSend
"""

[[plugins]]
repo = 'previm/previm'
hook_add = """
let g:previm_open_cmd = "open -a 'Google Chrome'"
"""

[[plugins]]
repo = 'machakann/vim-swap'
hook_add = """
omap i, <Plug>(swap-textobject-i)
xmap i, <Plug>(swap-textobject-i)
omap a, <Plug>(swap-textobject-a)
xmap a, <Plug>(swap-textobject-a)
"""

